name: "plant configuration"
description: "Site has solar resource class 2"

site:
  latitude: 30.6617
  longitude: -101.7096
  year: 2013
  elevation_m: 644
  time_zone: -6

  # array of polygons defining boundaries with x/y coords
  boundaries: [
    {
      x: [0.0, 1000.0, 1000.0, 0.0],
      y: [0.0, 0.0, 100.0, 1000.0],
    },
    {
      x: [2000.0, 2500.0, 2000.0],
      y: [2000.0, 2000.0, 2500.0],
    }
  ]

  solar_resource_filepath: "../11_hybrid_energy_plant/tech_inputs/weather/solar/30.6617_-101.7096_psmv3_60_2013.csv"

plant:
  plant_life: 30
  grid_connection: False # option, can be turned on or off
  ppa_price: 0.025 # $/kWh based on 2022 land based wind market report (ERCOT area ppa prices) https://www.energy.gov/sites/default/files/2022-08/land_based_wind_market_report_2202.pdf
  hybrid_electricity_estimated_cf: 0.492 #should equal 1 if grid_connection = True
  financial_analysis_start_year: 2029
  cost_year: 2022
  installation_time: 12 # months

finance_parameters:
  costing_general_inflation: 0.025 # used to adjust modeled costs to cost_year
  profast_general_inflation: 0.0 # 0
  pf_params: !include profast_params.yaml
  depreciation_method: "MACRS"
  depreciation_period: 7 # years - f
  discount_years:
    solar: 2022
