name: "driver_config"
description: "This analysis runs a hybrid plant to match the first example in H2I"

general:
  folder_output: ex_04_out
  create_om_reports: false
driver:
  design_of_experiments:
    flag: true
    debug_print: true
    generator: "csvgen"
    filename: "geoh2_doe_natural_sensitivity.csv"
    run_parallel: true
design_variables:
  geoh2_well_subsurface:
    site_prospectivity:
      flag: True
      units: "unitless"
      lower: 0.0
      upper: 1.0
    initial_wellhead_flow:
      flag: True
      units: "kg/h"
      lower: 1
      upper: 1000
    borehole_depth:
      flag: True
      units: "m"
      lower: 1
      upper: 1000
  geoh2_well_surface:
    electricity_price:
      flag: True
      units: "USD/kW/h"
      lower: 0
      upper: 1
    op_labor_rate:
      flag: True
      units: "USD/h"
      lower: 15
      upper: 100
objective:
  name: finance_subgroup_h2.LCOH
recorder:
    file: cases.sql
    overwrite_recorder: true
    flag: true
    includes: ['*']
    excludes: ['*wind_resource*']
