name: "plant_config"
description: "This plant is located west of the Wolf Hollow II NGCC power plant in Texas"

site:
  latitude: 32.34
  longitude: -98.27

plant:
  plant_life: 30

# finance_parameters:
#   cost_adjustment_parameters:
#     cost_year_adjustment_inflation: 0.025 # used to adjust modeled costs to target_dollar_year
#     target_dollar_year: 2024
