name: "technology_config"
description: "This hybrid plant produces geologic hydrogen"

technologies:
  geoh2:
    performance_model:
      model: "stim_geoh2_performance"
      model_class_name: StimulatedGeoH2PerformanceModel
      model_location: h2i_modules/public/stimulated_geoh2_plant.py
    cost_model:
      model: "stim_geoh2_cost"
      model_class_name: StimulatedGeoH2CostModel
      model_location: h2i_modules/public/stimulated_geoh2_plant.py
    financial_model:
      model: "stim_geoh2"
      model_class_name: StimulatedGeoH2FinanceModel
      model_location: h2i_modules/public/stimulated_geoh2_plant.py
    model_inputs:
      shared_parameters:
        well_lifetime: 20
      performance_parameters:
        rock_type: 'peridotite'
        grain_size: 0.00125
        serp_rate: 2.0e-10
        caprock_depth: 100
        borehole_depth: 1000
        inj_prod_distance: 100
        reaction_zone_width: 50
        iron_II_conc: 15
        bulk_density: 2700
        water_temp: 90
      cost_parameters:
        cost_year: 2020
        test_drill_cost: 500000
        permit_fees: 905
        acreage: 500
        rights_cost: 3
        completion_cost: 6700000
        success_chance: 80
        fixed_opex: 200000
        variable_opex: 0.298514591393227
