name: "technology_config"
description: "This hybrid plant produces iron"

technologies:
  iron_mine:
    performance_model:
      model: "iron_mine_performance"
    cost_model:
      model: "iron_mine_cost"
    model_inputs:
      shared_parameters:
        mine: "Northshore"
        taconite_pellet_type: "drg"
      performance_parameters:
        ore_cf_estimate: 0.9
        model_name: "martin_ore"
      cost_parameters:
        LCOE: 58.02
        LCOH: 7.10
        model_name: "martin_ore"
        varom_model_name: "martin_ore"
        installation_years: 3
        operational_year: 2035
        plant_life: 30
        gen_inflation: 0.025
        financial_assumptions:
          total income tax rate: 0.2574
          capital gains tax rate: 0.15
          leverage after tax nominal discount rate: 0.10893
          debt equity ratio of initial financing: 0.624788
          debt interest rate: 0.050049
  iron_transport:
    performance_model:
      model: "iron_transport_performance"
    cost_model:
      model: "iron_transport_cost"
    model_inputs:
      performance_parameters:
        find_closest_ship_site: False
        shipment_site: "Chicago"
      cost_parameters:
        transport_year: 2022
        cost_year: 2022
  iron_plant:
    performance_model:
      model: "humbert_electrowinning_performance"
    cost_model:
      model: "humbert_stinn_electrowinning_cost"
    model_inputs:
      shared_parameters:
        electrolysis_type: "ahe"
      performance_parameters:
        ore_fe_wt_pct: 65
        capacity_mw: 600
  wind:
    performance_model:
      model: "pysam_wind_plant_performance"
    cost_model:
      model: "atb_wind_cost"
    model_inputs:
      performance_parameters:
        num_turbines: 100
        turbine_rating_kw: 6000
        rotor_diameter: 170.
        hub_height: 115.
        create_model_from: "default"
        config_name: "WindPowerSingleOwner"
        pysam_options: !include pysam_options_6000MW.yaml
        run_recalculate_power_curve: False
        layout:
          layout_mode: "basicgrid"
          layout_options:
            row_D_spacing: 7.0
            turbine_D_spacing: 7.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: "square"
      cost_parameters:
        capex_per_kW: 1500.0
        opex_per_kW_per_year: 45
        cost_year: 2019
