name: "technology_config"
description: "This plant has offshore wind and wave energy connected to a power splitter that sends prescribed electricity to DOC and remainder to an electrolyzer for hydrogen production"

technologies:
  hopp:
    performance_model:
      model: "hopp"
      config: !include tech_inputs/hopp_config.yaml
    cost_model:
      model: "hopp"

  power_splitter:
    performance_model:
      model: "splitter_performance"
      config:
        split_mode: "ratio"
        split_ratio: 0.5

  doc:
    performance_model:
      model: "direct_ocean_capture_performance"
    cost_model:
      model: "direct_ocean_capture_cost"
    model_inputs:
      shared_parameters:
        power_single_ed_w: 240000. # W
        flow_rate_single_ed_m3s: 0.4 # m^3/s
        number_ed_min: 1
        number_ed_max: 10
        E_HCl: 0.05 # kWh/mol
        E_NaOH: 0.05 # kWh/mol
        y_ext: 0.9
        y_pur: 0.2
        y_vac: 0.6
        frac_ed_flow: 0.01
        use_storage_tanks: True
        initial_tank_volume_m3: 0. #m^3
        store_hours: 12. # hours
        sal: 33. # ppt
        temp_C: 12. # degrees Celsius
        dic_i: 0.0022 # mol/L
        pH_i: 8.1 # initial pH

      cost_parameters:
        infrastructure_type: "new"

  electrolyzer:
    performance_model:
      model: "eco_pem_electrolyzer_performance"
    cost_model:
      model: "basic_electrolyzer_cost"
    model_inputs:
      shared_parameters:
        rating: 80. # MW
        location: "onshore"
        electrolyzer_capex: 250

      performance_parameters:
        sizing:
          resize_for_enduse: False
          size_for: 'BOL' #'BOL' (generous) or 'EOL' (conservative)
          hydrogen_dmd:
        cluster_rating_MW: 20
        pem_control_type: 'basic'
        eol_eff_percent_loss: 13 #eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000. #number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: True #include degradation
        turndown_ratio: 0.1 #turndown_ratio = minimum_cluster_power/cluster_rating_MW

      cost_parameters:
        time_between_replacement: 10 # years

      financial_parameters:
        replacement_cost_percent: 0.15 # percent of capex - H2A default case
