name: "technology_config"
description: "This hybrid plant produces ammonia"

technologies:
  electrolyzer:
    performance_model:
      model: "eco_pem_electrolyzer_performance"
    cost_model:
      model: "singlitico_electrolyzer_cost"
    model_inputs:
      shared_parameters:
        rating: 640
        location: "onshore"
        electrolyzer_capex: 1295 # $/kW overnight installed capital costs for a 1 MW system in 2022 USD/kW (DOE hydrogen program record 24005	Clean Hydrogen Production Cost Scenarios with PEM Electrolyzer Technology 05/20/24) (https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/24005-clean-hydrogen-production-cost-pem-electrolyzer.pdf?sfvrsn=8cb10889_1)

      performance_parameters:
        compute_mode: "feedstock_size"
        size_by: "electricity"
        # compute_mode: "product_size"
        # size_by: "hydrogen"
        sizing:
          resize_for_enduse: False
          size_for: 'BOL' #'BOL' (generous) or 'EOL' (conservative)
          hydrogen_dmd:
        cluster_rating_MW: 40
        pem_control_type: 'basic'
        eol_eff_percent_loss: 10 #eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000 #number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: True #include degradation
        turndown_ratio: 0.1 #turndown_ratio = minimum_cluster_power/cluster_rating_MW

      financial_parameters:
        replacement_cost_percent: 0.15 # percent of capex - H2A default case
  feedstock_profile:
    performance_model:
      model: "feedstock_performance"
    cost_model:
      model: "feedstock_cost"
    model_inputs:
      shared_parameters:
        commodity: "electricity"
        unit: "kW"
      performance_parameters:
        compute_mode: "feedstock_size"
        profile: "elec_profile.csv"
      cost_parameters:
        buy_price: 0.07
  product_profile:
    performance_model:
      model: "product_performance"
    cost_model:
      model: "product_cost"
    model_inputs:
      shared_parameters:
        commodity: "hydrogen"
        unit: "kg/h"
      performance_parameters:
        compute_mode: "feedstock_size"
        profile: "h2_profile.csv"
      cost_parameters:
        sell_price: 1.50
        is_coproduct: False
