name: "technology_config"
description: "This hybrid plant produces iron"

technologies:
  iron_mine:
    performance_model:
      model: "iron_mine_performance"
    cost_model:
      model: "iron_mine_cost"
    model_inputs:
      shared_parameters:
        mine: "Northshore"
        taconite_pellet_type: "drg"
      performance_parameters:
        ore_cf_estimate: 0.9
        model_name: "martin_ore"
      cost_parameters:
        LCOE: 58.02
        LCOH: 7.10
        model_name: "martin_ore"
        varom_model_name: "martin_ore"
        installation_years: 3
        operational_year: 2035
        plant_life: 30

# baseline 843.37604007
