name: "technology_config"
description: "This hybrid plant produces iron"

technologies:
  iron:
    performance_model:
      model: "iron"
    model_inputs:
      cost_parameters:
        # h2_kgpy: 68583942.6460997 #1000000 #68583942.6460997
        LCOE: 58.02 #$/MWh
        LCOH: 7.10 #$/kg
        mine: 'Hibbing' #can be "Hibbing", "Northshore", "United", "Minorca" or "Tilden"
        post_type: 'eaf' #can be 'eaf' or 'none'
        winning_type: 'h2' #'h2' or 'ng'
        taconite_pellet_type: 'drg' #'drg' or 'std'
        cost_year: 2020

# baseline 843.37604007
