name: "technology_config"
description: "This hybrid plant produces iron"

technologies:
  iron:
    performance_model:
      model: "iron"
    model_inputs:
      cost_parameters:
        h2_kgpy: 1000000
        lcoe: .05802
        lcoh: 7.10
        cost_year: 2020
