name: "plant_config"
description: "This plant is located in MN, USA..."

site:
  latitude: 47.5233
  longitude: -92.5366
  elevation_m: 439.0
  time_zone: -5

  # array of polygons defining boundaries with x/y coords
  boundaries: [
    {
      x: [0.0, 1000.0, 1000.0, 0.0],
      y: [0.0, 0.0, 100.0, 1000.0],
    },
    {
      x: [2000.0, 2500.0, 2000.0],
      y: [2000.0, 2000.0, 2500.0],
    }
  ]

  resources:
    wind_resource:
      resource_model: "wind_toolkit_v2_api"
      resource_parameters:
        resource_year: 2013

# array of arrays containing left-to-right technology
# interconnections; can support bidirectional connections
# with the reverse definition.
# this will naturally grow as we mature the interconnected tech
technology_interconnections: [
  ["wind", "battery", "electricity", "cable"],
]

# array of arrays containing left-to-right source technology, dispatching technology, object_name
tech_to_dispatch_connections: [
  ["wind", "battery"],
  ["battery", "battery"],
]

resource_to_tech_connections: [
  # connect the wind resource to the wind technology
  ['wind_resource', 'wind', 'wind_resource_data'],
]

plant:
  plant_life: 30
  grid_connection: False # option, can be turned on or off
  ppa_price: 0.025 # $/kWh based on 2022 land based wind market report (ERCOT area ppa prices) https://www.energy.gov/sites/default/files/2022-08/land_based_wind_market_report_2202.pdf
  hybrid_electricity_estimated_cf: 0.492 #should equal 1 if grid_connection = True
  simulation:
    dt: 3600 # number of seconds per timestep
    n_timesteps: 8760 # number of time steps per simulation

finance_parameters:
  finance_groups:
    commodity: "electricity"
    finance_model: "ProFastComp"
    model_inputs:
      params:
        installation_time: 36 # months
        analysis_start_year: 2030
        inflation_rate: 0.0 # 0 for nominal analysis
        discount_rate: 0.09 # nominal return based on 2024 ATB baseline workbook for land-based wind
        debt_equity_ratio: 2.62 # 2024 ATB uses 72.4% debt for land-based wind
        property_tax_and_insurance: 0.03 # p-tax https://www.house.mn.gov/hrd/issinfo/clsrates.aspx # insurance percent of CAPEX estimated based on https://www.nrel.gov/docs/fy25osti/91775.pdf
        total_income_tax_rate: 0.257 # 0.257 tax rate in 2024 atb baseline workbook, value here is based on federal (21%) and state in MN (9.8)
        capital_gains_tax_rate: 0.15 # H2FAST default
        sales_tax_rate: 0.07375 # total state and local sales tax in St. Louis County https://taxmaps.state.mn.us/salestax/
        debt_interest_rate: 0.07 # based on 2024 ATB nominal interest rate for land-based wind
        debt_type: "Revolving debt" # can be "Revolving debt" or "One time loan". Revolving debt is H2FAST default and leads to much lower LCOH
        loan_period_if_used: 0 # H2FAST default, not used for revolving debt
        cash_onhand_months: 1 # H2FAST default
        admin_expense: 0.00 # percent of sales H2FAST default
      capital_items:
        depr_type: "MACRS" # can be "MACRS" or "Straight line" - MACRS may be better and can reduce LCOH by more than $1/kg and is spec'd in the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
        depr_period: 5 # years - for clean energy facilities as specified by the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
  cost_adjustment_parameters:
    target_dollar_year: 2022
    cost_year_adjustment_inflation: 0.025 # used to adjust modeled costs to cost_year
