name: "technology_config"
description: "This hybrid plant produces iron"

technologies:
  grid_feedstock: #electricity feedstock for iron ore
    performance_model:
      model: "feedstock_performance"
    cost_model:
      model: "feedstock_cost"
    model_inputs:
      shared_parameters:
        feedstock_type: "electricity"
        units: "MW"
      performance_parameters:
        rated_capacity: 30. # MW, need 27.913 MW per timestep for iron ore
      cost_parameters:
        cost_year: 2022
        price: 58.02 #USD/MW
        annual_cost: 0.
        start_up_cost: 0.

  mine_feedstock: #iron ore feedstock
    performance_model:
      model: "feedstock_performance"
    cost_model:
      model: "feedstock_cost"
    model_inputs:
      shared_parameters:
        feedstock_type: "crude_ore"
        units: "t/h"
      performance_parameters:
        rated_capacity: 2000. # need 828.50385048 t/h
      cost_parameters:
        cost_year: 2022
        price: 0.0
        annual_cost: 0.
        start_up_cost: 0.

  iron_mine:
    performance_model:
      model: "iron_mine_performance_martin"
    cost_model:
      model: "iron_mine_cost_martin"
    model_inputs:
      shared_parameters:
        mine: "Northshore"
        taconite_pellet_type: "drg"
        max_ore_production_rate_tonnes_per_hr: 250

  iron_transport:
    performance_model:
      model: "iron_transport_performance"
    cost_model:
      model: "iron_transport_cost"
    model_inputs:
      performance_parameters:
        find_closest_ship_site: False
        shipment_site: "Chicago"
      cost_parameters:
        transport_year: 2022
        cost_year: 2022

  ewin_grid_feedstock: #electricity feedstock for iron dri
    performance_model:
      model: "feedstock_performance"
    cost_model:
      model: "feedstock_cost"
    model_inputs:
      shared_parameters:
        feedstock_type: "electricity"
        units: "kW"
      performance_parameters:
        rated_capacity: 600000.
      cost_parameters:
        cost_year: 2022
        price: 0.05802 #USD/kW
        annual_cost: 0.
        start_up_cost: 0.

  iron_plant:
    performance_model:
      model: "humbert_electrowinning_performance"
    cost_model:
      model: "humbert_stinn_electrowinning_cost"
    model_inputs:
      shared_parameters:
        electrolysis_type: "ahe"
      performance_parameters:
        ore_fe_wt_pct: 65
        capacity_mw: 600
